boot order: Replace /env/boot/autboot script by barebox default boot mechanism.

diff --git a/arch/arm/boards/netx4000/env/boot/mmc b/arch/arm/boards/netx4000/env/boot/mmc
--- a/arch/arm/boards/netx4000/env/boot/mmc
+++ b/arch/arm/boards/netx4000/env/boot/mmc
@@ -1,16 +1,19 @@
 #!/bin/sh
 
+DEV1="/dev/disk0.0"
+DEV2="/dev/disk0.1"
+
 MP1="/mnt/part1"
 MP2="/mnt/part2"
 
-if [ -e /dev/disk0.0 ]; then
+if [ -e $DEV1 ]; then
 	mkdir -p $MP1
-	mount /dev/disk0.0 $MP1 && echo "Succesfully mounted mmc (part1) to" $MP1 || echo "Unable to mount mmc (part1)"
+	mount $DEV1 $MP1 && echo "Succesfully mounted mmc (part1) to" $MP1 || echo "Unable to mount mmc (part1)"
 fi
 
-if [ -e /dev/disk0.1 ]; then
+if [ -e $DEV2 ]; then
 	mkdir -p $MP2
-	mount /dev/disk0.1 $MP2 && echo "Succesfully mounted mmc (part2) to" $MP2 || echo "Unable to mount mmc (part2)"
+	mount $DEV2 $MP2 && echo "Succesfully mounted mmc (part2) to" $MP2 || echo "Unable to mount mmc (part2)"
 fi
 
 /env/boot/set_boot_env "/dev/mmcblk0p"
diff --git a/arch/arm/boards/netx4000/env/boot/nand b/arch/arm/boards/netx4000/env/boot/nand
--- a/arch/arm/boards/netx4000/env/boot/nand
+++ b/arch/arm/boards/netx4000/env/boot/nand
@@ -1,12 +1,14 @@
 #!/bin/sh
 
+DEV1="/dev/nand0.rootfs.ubi.rootfs"
+
 MP1="/mnt/part1"
 
 if [ -e /dev/nand0.rootfs ]; then
 	ubiattach /dev/nand0.rootfs
-	if [ -e /dev/nand0.rootfs.ubi.rootfs ]; then
+	if [ -e $DEV1 ]; then
 		mkdir -p $MP1
-		mount /dev/nand0.rootfs.ubi.rootfs $MP1 && echo "Succesfully mounted nand-flash (part1) to" $MP1 || echo "Unable to mount nand-flash (part1)"
+		mount $DEV1 $MP1 && echo "Succesfully mounted nand-flash (part1) to" $MP1 || echo "Unable to mount nand-flash (part1)"
 	fi
 fi
 
